# Generated by Django 5.2.6 on 2025-09-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
